configName: sam_d21_xpro
folderName: sam_d21_xpro
format_version: v1.0
frameworkPath: C:\projects\harmony_3
processor: ATSAMD21J18A
projectName: spi_bootloader_test_app_sam_d21_xpro
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMD21_DFP\3.6.144
